/*
 * App URI: 2025-04-04/design50497
 * Source Location: 2025-04-04/design50497.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.6190), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("2025-04-04/design50497", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// Generated JavaScript File for design50497.clx
			console.log('JavaScript for design50497 loaded.');;
			// End - User Script
			
			// Header
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("group_8133defa");
			group_1.style.css({
				"background-color" : "#FFFFFF",
				"border-bottom-color" : "#666666",
				"border-left-color" : "#666666",
				"border-top-color" : "#666666",
				"border-right-color" : "#666666"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container("group_cf8f35e5");
				var xYLayout_3 = new cpr.controls.layouts.XYLayout();
				group_2.setLayout(xYLayout_3);
				(function(container){
					var grid_1 = new cpr.controls.Grid("grd20e2c956");
					grid_1.init({
						"columns": [
							{"width": "100px"},
							{"width": "100px"},
							{"width": "100px"},
							{"width": "100px"},
							{"width": "100px"}
						],
						"header": {
							"rows": [{"height": "24px"}],
							"cells": [
								{
									"constraint": {"rowIndex": 0, "colIndex": 0},
									"configurator": function(cell){
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 1},
									"configurator": function(cell){
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 2},
									"configurator": function(cell){
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 3},
									"configurator": function(cell){
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 4},
									"configurator": function(cell){
									}
								}
							]
						},
						"detail": {
							"rows": [{"height": "24px"}],
							"cells": [
								{
									"constraint": {"rowIndex": 0, "colIndex": 0},
									"configurator": function(cell){
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 1},
									"configurator": function(cell){
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 2},
									"configurator": function(cell){
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 3},
									"configurator": function(cell){
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 4},
									"configurator": function(cell){
									}
								}
							]
						}
					});
					container.addChild(grid_1, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "1594.0px",
						"height": "430.0px"
					});
					var pageIndexer_1 = new cpr.controls.PageIndexer("instance_142cc290");
					container.addChild(pageIndexer_1, {
						"top": "450.0px",
						"left": "467.0px",
						"width": "660.0px",
						"height": "40.0px"
					});
				})(group_2);
				container.addChild(group_2, {
					"top": "335.0px",
					"left": "30.0px",
					"width": "1594.0px",
					"height": "510.0px"
				});
				var group_3 = new cpr.controls.Container("group_411fd1e2");
				group_3.style.css({
					"background-color" : "#FFF2CE"
				});
				var xYLayout_4 = new cpr.controls.layouts.XYLayout();
				group_3.setLayout(xYLayout_4);
				(function(container){
					var group_4 = new cpr.controls.Container("group_133d886f");
					var xYLayout_5 = new cpr.controls.layouts.XYLayout();
					group_4.setLayout(xYLayout_5);
					(function(container){
						var group_5 = new cpr.controls.Container("group_c0bf4519");
						var xYLayout_6 = new cpr.controls.layouts.XYLayout();
						group_5.setLayout(xYLayout_6);
						(function(container){
							var group_6 = new cpr.controls.Container("group_a171e87f");
							var xYLayout_7 = new cpr.controls.layouts.XYLayout();
							group_6.setLayout(xYLayout_7);
							(function(container){
								var group_7 = new cpr.controls.Container("group_76e8d021");
								var xYLayout_8 = new cpr.controls.layouts.XYLayout();
								group_7.setLayout(xYLayout_8);
								(function(container){
									var group_8 = new cpr.controls.Container("group_a64f8e82");
									var xYLayout_9 = new cpr.controls.layouts.XYLayout();
									group_8.setLayout(xYLayout_9);
									(function(container){
										var output_1 = new cpr.controls.Output("output_83aee283");
										output_1.value = "예산연도";
										container.addChild(output_1, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "59.0px",
											"height": "12.0px"
										});
									})(group_8);
									container.addChild(group_8, {
										"top": "14.0px",
										"left": "0.0px",
										"width": "59.0px",
										"height": "12.0px"
									});
									var group_9 = new cpr.controls.Container("group_7e0c7ebf");
									var xYLayout_10 = new cpr.controls.layouts.XYLayout();
									group_9.setLayout(xYLayout_10);
									(function(container){
										var comboBox_1 = new cpr.controls.ComboBox("instance_a5d34b80");
										comboBox_1.style.css({
											"background-color" : "#FFFFFF",
											"border-bottom-color" : "#717171",
											"border-left-color" : "#717171",
											"border-top-color" : "#717171",
											"border-right-color" : "#717171",
											"background-image" : "none"
										});
										container.addChild(comboBox_1, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "182.0px",
											"height": "40.0px"
										});
									})(group_9);
									container.addChild(group_9, {
										"top": "0.0px",
										"left": "71.0px",
										"width": "182.0px",
										"height": "40.0px"
									});
								})(group_7);
								container.addChild(group_7, {
									"top": "0.0px",
									"left": "0.0px",
									"width": "253.0px",
									"height": "40.0px"
								});
								var group_10 = new cpr.controls.Container("group_f77c18c4");
								var xYLayout_11 = new cpr.controls.layouts.XYLayout();
								group_10.setLayout(xYLayout_11);
								(function(container){
									var group_11 = new cpr.controls.Container("group_d8233d18");
									var xYLayout_12 = new cpr.controls.layouts.XYLayout();
									group_11.setLayout(xYLayout_12);
									(function(container){
										var output_2 = new cpr.controls.Output("output_ff86c225");
										output_2.value = "대상자구분";
										container.addChild(output_2, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "150.0px",
											"height": "12.0px"
										});
									})(group_11);
									container.addChild(group_11, {
										"top": "13.701492309570312px",
										"left": "0.0px",
										"width": "150.0px",
										"height": "12.0px"
									});
									var radioButton_1 = new cpr.controls.RadioButton("instance_c89ba878");
									radioButton_1.value = "전체";
									container.addChild(radioButton_1, {
										"top": "0.0px",
										"left": "162.0px",
										"width": "58.54016876220703px",
										"height": "39.402984619140625px"
									});
									var radioButton_2 = new cpr.controls.RadioButton("instance_3e35e7aa");
									radioButton_2.value = "성인 건강보험";
									container.addChild(radioButton_2, {
										"top": "0.0px",
										"left": "232.5401611328125px",
										"width": "123.13622283935547px",
										"height": "39.402984619140625px"
									});
									var radioButton_3 = new cpr.controls.RadioButton("instance_3e112adc");
									radioButton_3.value = "성인 의료급여";
									container.addChild(radioButton_3, {
										"top": "0.0px",
										"left": "367.6763916015625px",
										"width": "123.13622283935547px",
										"height": "39.402984619140625px"
									});
									var radioButton_4 = new cpr.controls.RadioButton("instance_1db3dc90");
									radioButton_4.value = "소아 의료급여";
									container.addChild(radioButton_4, {
										"top": "0.0px",
										"left": "502.8126220703125px",
										"width": "123.13622283935547px",
										"height": "39.402984619140625px"
									});
									var radioButton_5 = new cpr.controls.RadioButton("instance_926ff094");
									radioButton_5.value = "소아 건강보험";
									container.addChild(radioButton_5, {
										"top": "0.0px",
										"left": "637.9488525390625px",
										"width": "123.13622283935547px",
										"height": "39.402984619140625px"
									});
								})(group_10);
								container.addChild(group_10, {
									"top": "0.2985076904296875px",
									"left": "553.0px",
									"width": "761.0850830078125px",
									"height": "39.402984619140625px"
								});
							})(group_6);
							container.addChild(group_6, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "1514.0px",
								"height": "40.0px"
							});
							var group_12 = new cpr.controls.Container("group_4708c85a");
							var xYLayout_13 = new cpr.controls.layouts.XYLayout();
							group_12.setLayout(xYLayout_13);
							(function(container){
								var group_13 = new cpr.controls.Container("group_799f5452");
								var xYLayout_14 = new cpr.controls.layouts.XYLayout();
								group_13.setLayout(xYLayout_14);
								(function(container){
									var group_14 = new cpr.controls.Container("group_815e75fa");
									var xYLayout_15 = new cpr.controls.layouts.XYLayout();
									group_14.setLayout(xYLayout_15);
									(function(container){
										var output_3 = new cpr.controls.Output("output_db709cf2");
										output_3.value = "성명";
										container.addChild(output_3, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "30.0px",
											"height": "12.0px"
										});
									})(group_14);
									container.addChild(group_14, {
										"top": "14.0px",
										"left": "0.0px",
										"width": "30.0px",
										"height": "12.0px"
									});
									var group_15 = new cpr.controls.Container("group_5c2b2bfe");
									var xYLayout_16 = new cpr.controls.layouts.XYLayout();
									group_15.setLayout(xYLayout_16);
									(function(container){
										var button_1 = new cpr.controls.Button("instance_892a2a62");
										button_1.value = "Button";
										container.addChild(button_1, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "20.0px",
											"height": "20.0px"
										});
										var output_4 = new cpr.controls.Output("output_7bc5298b");
										output_4.value = "힌트 메시지";
										container.addChild(output_4, {
											"top": "4.5px",
											"left": "24.0px",
											"width": "70.0px",
											"height": "11.0px"
										});
									})(group_15);
									container.addChild(group_15, {
										"top": "83.0px",
										"left": "0.0px",
										"width": "94.0px",
										"height": "20.0px"
									});
									var group_16 = new cpr.controls.Container("group_5adfaaa5");
									var xYLayout_17 = new cpr.controls.layouts.XYLayout();
									group_16.setLayout(xYLayout_17);
									(function(container){
										var comboBox_2 = new cpr.controls.ComboBox("instance_b81ddd65");
										comboBox_2.style.css({
											"background-color" : "#FFFFFF",
											"border-bottom-color" : "#717171",
											"border-left-color" : "#717171",
											"border-top-color" : "#717171",
											"border-right-color" : "#717171",
											"background-image" : "none"
										});
										container.addChild(comboBox_2, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "182.0px",
											"height": "40.0px"
										});
									})(group_16);
									container.addChild(group_16, {
										"top": "0.0px",
										"left": "73.0px",
										"width": "182.0px",
										"height": "40.0px"
									});
								})(group_13);
								container.addChild(group_13, {
									"top": "0.0px",
									"left": "0.0px",
									"width": "255.0px",
									"height": "40.0px"
								});
								var group_17 = new cpr.controls.Container("group_96e03e04");
								var xYLayout_18 = new cpr.controls.layouts.XYLayout();
								group_17.setLayout(xYLayout_18);
								(function(container){
									var group_18 = new cpr.controls.Container("group_6a31364a");
									var xYLayout_19 = new cpr.controls.layouts.XYLayout();
									group_18.setLayout(xYLayout_19);
									(function(container){
										var output_5 = new cpr.controls.Output("output_f7c624ca");
										output_5.value = "주민등록번호";
										container.addChild(output_5, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "150.0px",
											"height": "12.0px"
										});
									})(group_18);
									container.addChild(group_18, {
										"top": "14.0px",
										"left": "0.0px",
										"width": "150.0px",
										"height": "12.0px"
									});
									var group_19 = new cpr.controls.Container("group_9f90420e");
									var xYLayout_20 = new cpr.controls.layouts.XYLayout();
									group_19.setLayout(xYLayout_20);
									(function(container){
										var button_2 = new cpr.controls.Button("instance_05d19cc6");
										button_2.value = "Button";
										container.addChild(button_2, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "20.0px",
											"height": "20.0px"
										});
										var output_6 = new cpr.controls.Output("output_16c91f5f");
										output_6.value = "힌트 메시지";
										container.addChild(output_6, {
											"top": "4.5px",
											"left": "24.0px",
											"width": "70.0px",
											"height": "11.0px"
										});
									})(group_19);
									container.addChild(group_19, {
										"top": "83.0px",
										"left": "0.0px",
										"width": "94.0px",
										"height": "20.0px"
									});
									var group_20 = new cpr.controls.Container("group_151c2d88");
									var xYLayout_21 = new cpr.controls.layouts.XYLayout();
									group_20.setLayout(xYLayout_21);
									(function(container){
										var inputBox_1 = new cpr.controls.InputBox("instance_413235e4");
										inputBox_1.style.css({
											"background-color" : "#FFFFFF",
											"border-bottom-color" : "#717171",
											"border-left-color" : "#717171",
											"border-top-color" : "#717171",
											"border-right-color" : "#717171",
											"background-image" : "none"
										});
										container.addChild(inputBox_1, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "160.0px",
											"height": "40.0px"
										});
										var output_7 = new cpr.controls.Output("output_5da4c64f");
										output_7.value = "-";
										container.addChild(output_7, {
											"top": "15.0px",
											"left": "166.0px",
											"width": "12.0px",
											"height": "11.0px"
										});
										var inputBox_2 = new cpr.controls.InputBox("instance_8e870e53");
										inputBox_2.style.css({
											"background-color" : "#FFFFFF",
											"border-bottom-color" : "#717171",
											"border-left-color" : "#717171",
											"border-top-color" : "#717171",
											"border-right-color" : "#717171",
											"background-image" : "none"
										});
										container.addChild(inputBox_2, {
											"top": "0.0px",
											"left": "185.0px",
											"width": "160.0px",
											"height": "40.0px"
										});
									})(group_20);
									container.addChild(group_20, {
										"top": "0.0px",
										"left": "162.0px",
										"width": "345.0px",
										"height": "40.0px"
									});
								})(group_17);
								container.addChild(group_17, {
									"top": "0.0px",
									"left": "555.0px",
									"width": "466.0px",
									"height": "40.0px"
								});
							})(group_12);
							container.addChild(group_12, {
								"top": "50.0px",
								"left": "0.0px",
								"width": "1514.0px",
								"height": "40.0px"
							});
						})(group_5);
						container.addChild(group_5, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "1514.0px",
							"height": "90.0px"
						});
						var group_21 = new cpr.controls.Container("group_2101275e");
						var xYLayout_22 = new cpr.controls.layouts.XYLayout();
						group_21.setLayout(xYLayout_22);
						(function(container){
							var group_22 = new cpr.controls.Container("group_240aec54");
							var xYLayout_23 = new cpr.controls.layouts.XYLayout();
							group_22.setLayout(xYLayout_23);
							(function(container){
								var group_23 = new cpr.controls.Container("group_2200cabf");
								var xYLayout_24 = new cpr.controls.layouts.XYLayout();
								group_23.setLayout(xYLayout_24);
								(function(container){
									var group_24 = new cpr.controls.Container("group_d41b75e1");
									var xYLayout_25 = new cpr.controls.layouts.XYLayout();
									group_24.setLayout(xYLayout_25);
									(function(container){
										var output_8 = new cpr.controls.Output("output_87bee67c");
										output_8.value = "퇴록여부";
										container.addChild(output_8, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "59.0px",
											"height": "12.0px"
										});
									})(group_24);
									container.addChild(group_24, {
										"top": "4.0px",
										"left": "0.0px",
										"width": "59.0px",
										"height": "12.0px"
									});
									var group_25 = new cpr.controls.Container("group_fef800c0");
									var xYLayout_26 = new cpr.controls.layouts.XYLayout();
									group_25.setLayout(xYLayout_26);
									(function(container){
										var radioButton_6 = new cpr.controls.RadioButton("instance_d0328af0");
										radioButton_6.value = "ALL";
										container.addChild(radioButton_6, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "54.0px",
											"height": "20.0px"
										});
										var radioButton_7 = new cpr.controls.RadioButton("instance_bf4f79a1");
										radioButton_7.value = "YES";
										container.addChild(radioButton_7, {
											"top": "0.0px",
											"left": "66.0px",
											"width": "55.0px",
											"height": "20.0px"
										});
										var radioButton_8 = new cpr.controls.RadioButton("instance_9c759c27");
										radioButton_8.value = "NO";
										container.addChild(radioButton_8, {
											"top": "0.0px",
											"left": "133.0px",
											"width": "49.0px",
											"height": "20.0px"
										});
									})(group_25);
									container.addChild(group_25, {
										"top": "0.0px",
										"left": "71.0px",
										"width": "182.0px",
										"height": "20.0px"
									});
								})(group_23);
								container.addChild(group_23, {
									"top": "0.0px",
									"left": "0.0px",
									"width": "253.0px",
									"height": "20.0px"
								});
							})(group_22);
							container.addChild(group_22, {
								"top": "10.0px",
								"left": "0.0px",
								"width": "253.0px",
								"height": "20.0px"
							});
							var group_26 = new cpr.controls.Container("group_68ac922d");
							var xYLayout_27 = new cpr.controls.layouts.XYLayout();
							group_26.setLayout(xYLayout_27);
							(function(container){
								var group_27 = new cpr.controls.Container("group_e5edb1b9");
								var xYLayout_28 = new cpr.controls.layouts.XYLayout();
								group_27.setLayout(xYLayout_28);
								(function(container){
									var group_28 = new cpr.controls.Container("group_b4e0e1b1");
									var xYLayout_29 = new cpr.controls.layouts.XYLayout();
									group_28.setLayout(xYLayout_29);
									(function(container){
										var output_9 = new cpr.controls.Output("output_3acb1984");
										output_9.value = "보건소장 위임여부";
										container.addChild(output_9, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "150.0px",
											"height": "12.0px"
										});
									})(group_28);
									container.addChild(group_28, {
										"top": "4.0px",
										"left": "0.0px",
										"width": "150.0px",
										"height": "12.0px"
									});
									var radioButton_9 = new cpr.controls.RadioButton("instance_e0127ced");
									radioButton_9.value = "NO";
									container.addChild(radioButton_9, {
										"top": "0.0px",
										"left": "162.0px",
										"width": "49.0px",
										"height": "20.0px"
									});
									var group_29 = new cpr.controls.Container("group_d38fe388");
									var xYLayout_30 = new cpr.controls.layouts.XYLayout();
									group_29.setLayout(xYLayout_30);
									(function(container){
										var button_3 = new cpr.controls.Button("instance_34454575");
										button_3.value = "Button";
										container.addChild(button_3, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "20.0px",
											"height": "20.0px"
										});
										var output_10 = new cpr.controls.Output("output_a0684d15");
										output_10.value = "힌트 메시지";
										container.addChild(output_10, {
											"top": "4.5px",
											"left": "24.0px",
											"width": "70.0px",
											"height": "11.0px"
										});
									})(group_29);
									container.addChild(group_29, {
										"top": "83.0px",
										"left": "0.0px",
										"width": "94.0px",
										"height": "20.0px"
									});
									var radioButton_10 = new cpr.controls.RadioButton("instance_b392debc");
									radioButton_10.value = "ALL";
									container.addChild(radioButton_10, {
										"top": "0.0px",
										"left": "223.0px",
										"width": "54.0px",
										"height": "20.0px"
									});
									var radioButton_11 = new cpr.controls.RadioButton("instance_25cf0769");
									radioButton_11.value = "YES";
									container.addChild(radioButton_11, {
										"top": "0.0px",
										"left": "289.0px",
										"width": "55.0px",
										"height": "20.0px"
									});
								})(group_27);
								container.addChild(group_27, {
									"top": "14.0px",
									"left": "0.0px",
									"width": "305.0px",
									"height": "20.0px"
								});
								var group_30 = new cpr.controls.Container("group_4b29b4cd");
								var xYLayout_31 = new cpr.controls.layouts.XYLayout();
								group_30.setLayout(xYLayout_31);
								(function(container){
									var button_4 = new cpr.controls.Button("instance_32f6fb5a");
									button_4.value = "초기화";
									button_4.style.css({
										"background-color" : "#FFFFFF",
										"border-bottom-color" : "#1d1d1d",
										"border-left-color" : "#1d1d1d",
										"border-top-color" : "#1d1d1d",
										"border-right-color" : "#1d1d1d",
										"background-image" : "none"
									});
									container.addChild(button_4, {
										"top": "0.0px",
										"left": "0.0px",
										"width": "91.0px",
										"height": "48.0px"
									});
									var button_5 = new cpr.controls.Button("instance_d325d742");
									button_5.value = "조회";
									button_5.style.css({
										"background-color" : "#FFC20E",
										"background-image" : "none"
									});
									container.addChild(button_5, {
										"top": "0.0px",
										"left": "99.0px",
										"width": "91.0px",
										"height": "48.0px"
									});
								})(group_30);
								container.addChild(group_30, {
									"top": "0.0px",
									"left": "785.0px",
									"width": "169.0px",
									"height": "48.0px"
								});
							})(group_26);
							container.addChild(group_26, {
								"top": "-4.0px",
								"left": "553.0px",
								"width": "961.0px",
								"height": "48.0px"
							});
						})(group_21);
						container.addChild(group_21, {
							"top": "100.0px",
							"left": "0.0px",
							"width": "1514.0px",
							"height": "40.0px"
						});
					})(group_4);
					container.addChild(group_4, {
						"top": "20.0px",
						"left": "40.0px",
						"width": "1514.0px",
						"height": "140.0px"
					});
				})(group_3);
				container.addChild(group_3, {
					"top": "76.0px",
					"left": "30.0px",
					"width": "1594.0px",
					"height": "180.0px"
				});
				var group_31 = new cpr.controls.Container("group_bb472159");
				var xYLayout_32 = new cpr.controls.layouts.XYLayout();
				group_31.setLayout(xYLayout_32);
				(function(container){
					var group_32 = new cpr.controls.Container("group_49c5c0d0");
					var xYLayout_33 = new cpr.controls.layouts.XYLayout();
					group_32.setLayout(xYLayout_33);
					(function(container){
						var group_33 = new cpr.controls.Container("group_df7d5a7a");
						var xYLayout_34 = new cpr.controls.layouts.XYLayout();
						group_33.setLayout(xYLayout_34);
						(function(container){
							var output_11 = new cpr.controls.Output("output_af25c752");
							output_11.value = "우리보건소 등록카드 ";
							container.addChild(output_11, {
								"top": "3.0px",
								"left": "0.0px",
								"width": "190.0px",
								"height": "20.0px"
							});
						})(group_33);
						container.addChild(group_33, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "219.783203125px",
							"height": "24.0px"
						});
					})(group_32);
					container.addChild(group_32, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "219.783203125px",
						"height": "24.0px"
					});
					var group_34 = new cpr.controls.Container("group_9664949c");
					var xYLayout_35 = new cpr.controls.layouts.XYLayout();
					group_34.setLayout(xYLayout_35);
					(function(container){
						var button_6 = new cpr.controls.Button("instance_0e49a1d8");
						button_6.value = "Button";
						container.addChild(button_6, {
							"top": "10.0px",
							"left": "10.0px",
							"width": "403.0px",
							"height": "24.0px"
						});
					})(group_34);
					container.addChild(group_34, {
						"top": "0.0px",
						"left": "1169.0px",
						"width": "423.0px",
						"height": "44.0px"
					});
				})(group_31);
				container.addChild(group_31, {
					"top": "30.0px",
					"left": "30.0px",
					"width": "1592.0px",
					"height": "44.0px"
				});
				var group_35 = new cpr.controls.Container("group_ceccf997");
				var xYLayout_36 = new cpr.controls.layouts.XYLayout();
				group_35.setLayout(xYLayout_36);
				(function(container){
					var group_36 = new cpr.controls.Container("group_1cb1c07c");
					var xYLayout_37 = new cpr.controls.layouts.XYLayout();
					group_36.setLayout(xYLayout_37);
					(function(container){
						var button_7 = new cpr.controls.Button("instance_ad0c7e47");
						button_7.value = "엑셀다운로드";
						button_7.style.css({
							"background-color" : "#FFFFFF",
							"border-bottom-color" : "#1d1d1d",
							"border-left-color" : "#1d1d1d",
							"border-top-color" : "#1d1d1d",
							"border-right-color" : "#1d1d1d",
							"background-image" : "none"
						});
						container.addChild(button_7, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "118.0px",
							"height": "32.0px"
						});
						var group_37 = new cpr.controls.Container("group_8da6c1e3");
						var xYLayout_38 = new cpr.controls.layouts.XYLayout();
						group_37.setLayout(xYLayout_38);
						container.addChild(group_37, {
							"top": "9.0px",
							"left": "11.0px",
							"width": "14.0px",
							"height": "14.0px"
						});
					})(group_36);
					container.addChild(group_36, {
						"top": "6.0px",
						"left": "1476.0px",
						"width": "118.0px",
						"height": "32.0px"
					});
					var output_12 = new cpr.controls.Output("output_984a7036");
					output_12.value = "총 123회";
					container.addChild(output_12, {
						"top": "18.0px",
						"left": "0.0px",
						"width": "1594.0px",
						"height": "12.0px"
					});
				})(group_35);
				container.addChild(group_35, {
					"top": "286.0px",
					"left": "30.0px",
					"width": "1594.0px",
					"height": "49.0px"
				});
				var group_38 = new cpr.controls.Container("group_e8b31ade");
				var xYLayout_39 = new cpr.controls.layouts.XYLayout();
				group_38.setLayout(xYLayout_39);
				(function(container){
					var button_8 = new cpr.controls.Button("instance_dc6c179a");
					button_8.value = "삭제";
					button_8.style.css({
						"background-color" : "#FFFFFF",
						"border-bottom-color" : "#1d1d1d",
						"border-left-color" : "#1d1d1d",
						"border-top-color" : "#1d1d1d",
						"border-right-color" : "#1d1d1d",
						"background-image" : "none"
					});
					container.addChild(button_8, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "46.0px",
						"height": "32.0px"
					});
					var button_9 = new cpr.controls.Button("instance_847a6c9d");
					button_9.value = "퇴록";
					button_9.style.css({
						"background-color" : "#FFFFFF",
						"border-bottom-color" : "#1d1d1d",
						"border-left-color" : "#1d1d1d",
						"border-top-color" : "#1d1d1d",
						"border-right-color" : "#1d1d1d",
						"background-image" : "none"
					});
					container.addChild(button_9, {
						"top": "0.0px",
						"left": "56.0px",
						"width": "46.0px",
						"height": "32.0px"
					});
				})(group_38);
				container.addChild(group_38, {
					"top": "292.0px",
					"left": "1395.0px",
					"width": "102.0px",
					"height": "32.0px"
				});
				var group_39 = new cpr.controls.Container("group_ca82bc2e");
				var xYLayout_40 = new cpr.controls.layouts.XYLayout();
				group_39.setLayout(xYLayout_40);
				(function(container){
					var group_40 = new cpr.controls.Container("group_24556787");
					var xYLayout_41 = new cpr.controls.layouts.XYLayout();
					group_40.setLayout(xYLayout_41);
					(function(container){
						var button_10 = new cpr.controls.Button("instance_d4163e7d");
						button_10.value = "소아의료급여카드 등록";
						button_10.style.css({
							"background-color" : "#FFFFFF",
							"border-bottom-color" : "#1d1d1d",
							"border-left-color" : "#1d1d1d",
							"border-top-color" : "#1d1d1d",
							"border-right-color" : "#1d1d1d",
							"background-image" : "none"
						});
						container.addChild(button_10, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "238.0px",
							"height": "56.0px"
						});
						var group_41 = new cpr.controls.Container("group_9863905c");
						var xYLayout_42 = new cpr.controls.layouts.XYLayout();
						group_41.setLayout(xYLayout_42);
						container.addChild(group_41, {
							"top": "14.0px",
							"left": "198.0px",
							"width": "23.999662399291992px",
							"height": "23.99997329711914px"
						});
					})(group_40);
					container.addChild(group_40, {
						"top": "0.0px",
						"left": "744.0px",
						"width": "238.0px",
						"height": "56.0px"
					});
					var group_42 = new cpr.controls.Container("group_a7611146");
					var xYLayout_43 = new cpr.controls.layouts.XYLayout();
					group_42.setLayout(xYLayout_43);
					(function(container){
						var button_11 = new cpr.controls.Button("instance_10bbd236");
						button_11.value = "소아건강보험카드 등록";
						button_11.style.css({
							"background-color" : "#FFFFFF",
							"border-bottom-color" : "#1d1d1d",
							"border-left-color" : "#1d1d1d",
							"border-top-color" : "#1d1d1d",
							"border-right-color" : "#1d1d1d",
							"background-image" : "none"
						});
						container.addChild(button_11, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "238.0px",
							"height": "56.0px"
						});
						var group_43 = new cpr.controls.Container("group_e39af72c");
						var xYLayout_44 = new cpr.controls.layouts.XYLayout();
						group_43.setLayout(xYLayout_44);
						container.addChild(group_43, {
							"top": "14.0px",
							"left": "198.0px",
							"width": "23.999662399291992px",
							"height": "23.99997329711914px"
						});
					})(group_42);
					container.addChild(group_42, {
						"top": "0.0px",
						"left": "496.0px",
						"width": "238.0px",
						"height": "56.0px"
					});
					var group_44 = new cpr.controls.Container("group_ce4b66a9");
					var xYLayout_45 = new cpr.controls.layouts.XYLayout();
					group_44.setLayout(xYLayout_45);
					(function(container){
						var button_12 = new cpr.controls.Button("instance_fb223966");
						button_12.value = "성인의료급여카드 등록";
						button_12.style.css({
							"background-color" : "#FFFFFF",
							"border-bottom-color" : "#1d1d1d",
							"border-left-color" : "#1d1d1d",
							"border-top-color" : "#1d1d1d",
							"border-right-color" : "#1d1d1d",
							"background-image" : "none"
						});
						container.addChild(button_12, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "238.0px",
							"height": "56.0px"
						});
					})(group_44);
					container.addChild(group_44, {
						"top": "0.0px",
						"left": "248.0px",
						"width": "238.0px",
						"height": "56.0px"
					});
					var group_45 = new cpr.controls.Container("group_e705875d");
					var xYLayout_46 = new cpr.controls.layouts.XYLayout();
					group_45.setLayout(xYLayout_46);
					(function(container){
						var button_13 = new cpr.controls.Button("instance_4a7706bc");
						button_13.value = "성인건강보험카드 등록";
						button_13.style.css({
							"background-color" : "#FFFFFF",
							"border-bottom-color" : "#1d1d1d",
							"border-left-color" : "#1d1d1d",
							"border-top-color" : "#1d1d1d",
							"border-right-color" : "#1d1d1d",
							"background-image" : "none"
						});
						container.addChild(button_13, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "238.0px",
							"height": "56.0px"
						});
					})(group_45);
					container.addChild(group_45, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "238.0px",
						"height": "56.0px"
					});
				})(group_39);
				container.addChild(group_39, {
					"top": "845.0px",
					"left": "632.0px",
					"width": "982.0px",
					"height": "56.0px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0.0px",
				"left": "0.0px",
				"width": "1654.0px",
				"height": "940.0px"
			});
		}
	});
	app.title = "design50497";
	cpr.core.Platform.INSTANCE.register(app);
})();
