/*
 * App URI: prototype
 * Source Location: prototype.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.6190), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("prototype", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1440px)", "EXB-FULL");
			app.supportMedia("all and (min-width: 1024px) and (max-width: 1439.984px)", "EXB-DIV");
			app.supportMedia("all and (min-width: 768px) and (max-width: 1023.984px)", "EXB-PART");
			app.supportMedia("all and (max-width: 767.984px)", "EXB-POP");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["content-wrapper"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.horizontalSpacing = "12px";
			formLayout_1.verticalSpacing = "12px";
			formLayout_1.topMargin = "10px";
			formLayout_1.rightMargin = "16px";
			formLayout_1.bottomMargin = "10px";
			formLayout_1.leftMargin = "16px";
			formLayout_1.setColumns(["1fr"]);
			formLayout_1.setRows(["30px", "1fr", "0px"]);
			formLayout_1.setRowAutoSizing(2, true);
			container.setLayout(formLayout_1);
			
			// UI Configuration
			var userDefinedControl_1 = new udc.com.udcComAppHeader("udcComAppHeader");
			container.addChild(userDefinedControl_1, {
				"colIndex": 0,
				"rowIndex": 0
			});
			
			var group_1 = new cpr.controls.Container("grpData");
			group_1.style.setClasses(["content-body"]);
			var formLayout_2 = new cpr.controls.layouts.FormLayout();
			formLayout_2.scrollable = false;
			formLayout_2.horizontalSpacing = "12px";
			formLayout_2.verticalSpacing = "12px";
			formLayout_2.topMargin = "0px";
			formLayout_2.rightMargin = "0px";
			formLayout_2.bottomMargin = "0px";
			formLayout_2.leftMargin = "0px";
			formLayout_2.setColumns(["1fr"]);
			formLayout_2.setRows(["1fr"]);
			group_1.setLayout(formLayout_2);
			container.addChild(group_1, {
				"colIndex": 0,
				"rowIndex": 1
			});
			
			var group_2 = new cpr.controls.Container("grpFooter");
			group_2.style.setClasses(["content-footer"]);
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.scrollable = false;
			verticalLayout_1.spacing = 12;
			group_2.setLayout(verticalLayout_1);
			(function(container){
				var group_3 = new cpr.controls.Container();
				group_3.style.setClasses(["footer-button-group"]);
				var formLayout_3 = new cpr.controls.layouts.FormLayout();
				formLayout_3.scrollable = false;
				formLayout_3.horizontalSpacing = "32px";
				formLayout_3.verticalSpacing = "0px";
				formLayout_3.topMargin = "0px";
				formLayout_3.rightMargin = "0px";
				formLayout_3.bottomMargin = "0px";
				formLayout_3.leftMargin = "0px";
				formLayout_3.setColumns(["0px", "1fr"]);
				formLayout_3.setColumnAutoSizing(0, true);
				formLayout_3.setRows(["1fr"]);
				group_3.setLayout(formLayout_3);
				(function(container){
					var group_4 = new cpr.controls.Container();
					var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
					flowLayout_1.scrollable = false;
					flowLayout_1.horizontalSpacing = 6;
					flowLayout_1.verticalSpacing = 6;
					group_4.setLayout(flowLayout_1);
					container.addChild(group_4, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var group_5 = new cpr.controls.Container();
					var flowLayout_2 = new cpr.controls.layouts.FlowLayout();
					flowLayout_2.scrollable = false;
					flowLayout_2.horizontalSpacing = 6;
					flowLayout_2.verticalSpacing = 6;
					flowLayout_2.horizontalAlign = "right";
					group_5.setLayout(flowLayout_2);
					(function(container){
						var button_1 = new cpr.controls.Button("btn1");
						button_1.value = "버튼";
						button_1.style.setClasses(["btn-secondary-01"]);
						container.addChild(button_1, {
							"autoSize": "width",
							"width": "40px",
							"height": "28px"
						});
					})(group_5);
					container.addChild(group_5, {
						"colIndex": 1,
						"rowIndex": 0
					});
				})(group_3);
				container.addChild(group_3, {
					"autoSize": "height",
					"width": "1408px",
					"height": "28px"
				});
			})(group_2);
			container.addChild(group_2, {
				"colIndex": 0,
				"rowIndex": 2
			});
		}
	});
	app.title = "prototype";
	cpr.core.Platform.INSTANCE.register(app);
})();
