/*
 * App URI: design/20250403
 * Source Location: design/20250403.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.6190), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("design/20250403", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * 20250403.js
			 * Created at 2025. 4. 3. 오전 10:57:02.
			 *
			 * @author LCM
			 ************************************************/

			/*
			 * "Button" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(e){
				var btn1 = e.control;
				app.lookup("sms1").send();
			}

			/*
			 * "Button" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				var button = e.control;
				app.lookup("sms2").send();
			};
			// End - User Script
			
			// Header
			var submission_1 = new cpr.protocols.Submission("sms1");
			submission_1.action = "../design/convert.do";
			submission_1.mediaType = "multipart/form-data";
			app.register(submission_1);
			
			var submission_2 = new cpr.protocols.Submission("sms2");
			submission_2.action = "../design/test.do";
			app.register(submission_2);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button("btn1");
			button_1.value = "Button";
			if(typeof onBtn1Click == "function") {
				button_1.addEventListener("click", onBtn1Click);
			}
			container.addChild(button_1, {
				"top": "188px",
				"left": "307px",
				"width": "322px",
				"height": "147px"
			});
			
			var button_2 = new cpr.controls.Button();
			button_2.value = "Button";
			if(typeof onButtonClick == "function") {
				button_2.addEventListener("click", onButtonClick);
			}
			container.addChild(button_2, {
				"top": "419px",
				"left": "307px",
				"width": "312px",
				"height": "162px"
			});
			
			var radioButton_1 = new cpr.controls.RadioButton("rdb1");
			container.addChild(radioButton_1, {
				"top": "349px",
				"left": "788px",
				"width": "10px",
				"height": "10px"
			});
		}
	});
	app.title = "20250403";
	cpr.core.Platform.INSTANCE.register(app);
})();
