/*
 * App URI: design/TST20250307
 * Source Location: design/TST20250307.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.6190), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("design/TST20250307", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * TST20250307.js
			 * Created at 2025. 3. 7. 오후 1:23:48.
			 *
			 * @author LCM
			 ************************************************/

			/*
			 * "Button" 버튼(btn1)에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onBtn1Click(e){
				var btn1 = e.control;
				app.lookup("sms1").send();
			};
			// End - User Script
			
			// Header
			var submission_1 = new cpr.protocols.Submission("sms1");
			submission_1.action = "../Lcm/testDesign.do";
			submission_1.mediaType = "multipart/form-data";
			submission_1.responseType = "blob";
			app.register(submission_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button("btn1");
			button_1.value = "Button";
			if(typeof onBtn1Click == "function") {
				button_1.addEventListener("click", onBtn1Click);
			}
			container.addChild(button_1, {
				"top": "175px",
				"left": "270px",
				"width": "343px",
				"height": "179px"
			});
		}
	});
	app.title = "TST20250307";
	cpr.core.Platform.INSTANCE.register(app);
})();
